/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ni.edu.uni.programacion.backend.dao.implementation.JsonVehicleDaoImpl;
import ni.edu.uni.programacion.backend.pojo.Vehicle;
import ni.edu.uni.programacion.backend.pojo.VehicleSubModel;
import ni.edu.uni.programacion.controllers.PnlVehicleController;
import ni.edu.uni.programacion.views.VehicleMain;

/**
 *
 * @author Usuario
 */
public class PnlVehiclesList extends javax.swing.JPanel {

    private VehicleSubModel vehicleSubModel;
    private Vehicle vehiculo;
    private PnlVehicleController vehicleController;
    private PnlVehicle pnlVehicle;
     private JsonVehicleDaoImpl vjdao;
    
    public PnlVehiclesList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);

        txtSearch.setMinimumSize(new java.awt.Dimension(30, 24));
        txtSearch.setPreferredSize(new java.awt.Dimension(300, 25));
        jPanel1.add(txtSearch);

        btnView.setText("View");
        btnView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable2.setBackground(new java.awt.Color(204, 255, 255));
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Year", "Make", "Model", "Style", "VIN"
            }
        ));
        jTable2.setRowHeight(30);
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        
     try {
            vjdao = new JsonVehicleDaoImpl();
          
            //vjdao.create(v);
            
            List<Vehicle> vehicles = (List<Vehicle>) vjdao.getAll();
            
            String matris[][] = new String[vehicles.size()][5];
            for(int i = 0; i < vehicles.size(); i++){
                String año = String.valueOf(vehicles.get(i).getYear());
                matris[i][0] = año;
                matris[i][1] = vehicles.get(i).getMake();
                matris[i][2] = vehicles.get(i).getModel();
                matris[i][3] = vehicles.get(i).getStyle();
                matris[i][4] = vehicles.get(i).getVin();
                
            }
            jTable2.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Year", "Make", "Model", "Style", "VIN"
            }
        ));
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VehicleMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VehicleMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
